name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update version in package.json
        shell: bash
        run: |
          sed -i "3s/.*/  \"version\": \"${{ github.ref_name }}\",/" package.json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: THG-CustomerZen/GitHub/.github/actions/github-login@master
        with:
          username: ${{ secrets.GH_SA_USERNAME }}
          password: ${{ secrets.PAT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@thg-customerzen"
      - run: yarn install --frozen-lockfile && yarn build:lib
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - run: cd dist-lib && yarn publish --non-interactive --access public --registry=https://npm.pkg.github.com/
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
