name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Update version in package.json
        shell: bash
        run: |
          sed -i "3s/.*/  \"version\": \"${{ github.ref_name }}\",/" package.json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - run: npm install
      - run: npm run build
      - run: cd dist-lib && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT_TOKEN}}
