name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Configure npm for GitHub Package Registry
        run: |
          echo "@thg-customerzen:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT_TOKEN }}" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
      - run: yarn install --frozen-lockfile

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Update version in package.json
        shell: bash
        run: |
          sed -i "3s/.*/  \"version\": \"${{ github.ref_name }}\",/" package.json
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@thg-customerzen"
      - name: Configure npm for GitHub Package Registry
        run: |
          echo "@thg-customerzen:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT_TOKEN }}" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
      - run: yarn install --frozen-lockfile && yarn build:lib
      - run: cd dist-lib && yarn publish --non-interactive --access public --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}
