name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@thg-customerzen"
      - name: Login to GitHub Container Registry
        uses: THG-CustomerZen/GitHub/.github/actions/github-login@master
        with:
          username: ${{ secrets.GH_SA_USERNAME }}
          password: ${{ secrets.PAT_TOKEN }}
      - run: |
          yarn install --frozen-lockfile && yarn build:lib
          echo -e "@thg-customerzen:registry=https://npm.pkg.github.com/\\n//npm.pkg.github.com/:_authToken=${{ secrets.PAT_TOKEN }}" >> .npmrc
          cd dist-lib && yarn publish --registry=https://npm.pkg.github.com/
